image: maven:3.3.9
#image: jimador/docker-jdk-8-maven-node

pipelines:
  default:
    - step:
        script:
          - mvn --version
          - mvn clean install
#          - cd tests
#          - npm install -g jasmine-node
#          - npm install --save-dev frisby
#          - jasmine-node .