image: eclipse-temurin:21-jdk-alpine

options:
  max-time: 10

stepdefinitions:
  - build: &build
      name: Build
      caches:
        - maven
      script:
        - java -version
        - mvn --version
        - mvn clean install -DskipITs
        - rm -rf ~/.m2/repository/org/entrystore/
      artifacts:
        - target/rowstore-*.jar
  - testpg: &testpg
      name: Integration Test PostgreSQL
      caches:
        - maven
        - docker
      script:
        - java -version
        - mvn --version
        - export TESTCONTAINERS_RYUK_DISABLED=true
        - mvn verify -Dsurefire.skip=true
      services:
        - docker
  - deploy: &deploy
      name: Deploy
      script:
        - gpg --version
        - echo $GPG_SIGN_KEY | base64 -d | gpg --import
        - gpg --list-secret-keys
        - export VERSION=`cat VERSION.txt` && echo $VERSION
        # We allow semantic versioning plus x.y-z (e.g. 4.10-SNAPSHOT which does not exactly conform to semver)
        - echo $VERSION | grep -P -q '^(0|[1-9]\d*)\.(0|[1-9]\d*)(\.*)(0*|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
        - export FILE_BASE="rowstore-$VERSION" && echo $FILE_BASE
        - sha256sum target/rowstore-${VERSION}.jar > target/${FILE_BASE}.jar.sha256
        - gpg --clearsign --default-key 4C12C06EE69EBA383C1A47C61010232068FF1D01 target/${FILE_BASE}.jar.sha256
        - scp -v target/${FILE_BASE}.jar target/${FILE_BASE}.jar.sha256.asc deploy@meta1.metasolutions.se:/var/www/entrystore.org/download/rowstore/
        - if [ $BITBUCKET_BRANCH == "develop" ]; then ssh deploy@meta1.metasolutions.se "echo $VERSION > /var/www/entrystore.org/download/rowstore/develop.version" ; elif [ $BITBUCKET_BRANCH == "master" ]; then ssh deploy@meta1.metasolutions.se "echo $VERSION > /var/www/entrystore.org/download/rowstore/latest.version" ; fi
  - dockerhub: &dockerhub
      name: Docker Hub
      script:
        - docker version
        - export VERSION=`cat VERSION.txt` && echo $VERSION
        - export VERSION_MAJOR_MINOR=${VERSION%.*} && echo $VERSION_MAJOR_MINOR
        - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
        - docker build --pull --no-cache --tag metasolutions/rowstore:$VERSION .
        - docker push metasolutions/rowstore:$VERSION
        - if [ $BITBUCKET_BRANCH == "develop" ]; then docker tag metasolutions/rowstore:$VERSION metasolutions/rowstore:develop ; docker push metasolutions/rowstore:develop ; fi
        - if [ $BITBUCKET_BRANCH == "master" ]; then docker tag metasolutions/rowstore:$VERSION metasolutions/rowstore:$VERSION_MAJOR_MINOR ; docker push metasolutions/rowstore:$VERSION_MAJOR_MINOR ; fi
      services:
        - docker
      caches:
        - docker

pipelines:
  default:
    - step: *build
    - parallel:
      - step: *testpg
  branches:
    master:
      - step: *build
      - parallel:
        - step: *testpg
      - step: *deploy
      - step: *dockerhub
    develop:
      - step: *build
      - parallel:
        - step: *testpg
      - step: *deploy
      - step: *dockerhub
