image: metasolutions/openjdk-node-postgresql

options:
  max-time: 10

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn --version
          - gpg --version
          - echo $GPG_SIGN_KEY | base64 -d | gpg --import
          - gpg --list-secret-keys
          - export VERSION=`cat VERSION.txt` && echo $VERSION
          # We allow semantic versioning plus x.y-z (e.g. 4.10-SNAPSHOT which does not exactly conform to semver)
          - echo $VERSION | grep -P -q '^(0|[1-9]\d*)\.(0|[1-9]\d*)(\.*)(0*|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
          - mvn clean install
          - /etc/init.d/postgresql start
          - sudo -u postgres sh -c 'createuser rowstoretest & createdb rowstoretest'
          - sudo -u postgres psql -c "ALTER USER rowstoretest PASSWORD 'rowstoretestpw';"
          - chmod +x standalone/target/dist/bin/rowstore
          - standalone/target/dist/bin/rowstore tests/rowstore_tests.json 8282 &
          - sleep 5
          - pushd tests
          - npm install -g jasmine-node
          - npm install frisby@0.8.5
          - jasmine-node .
          - popd
          - export FILE_BASE="rowstore-$VERSION" && echo $FILE_BASE
          - ( cd standalone/target/dist/ && tar czf ${FILE_BASE}.tar.gz * && sha256sum ${FILE_BASE}.tar.gz > ${FILE_BASE}.tar.gz.sha256 && gpg --clearsign --default-key 4C12C06EE69EBA383C1A47C61010232068FF1D01 ${FILE_BASE}.tar.gz.sha256 )
          - export FILE_BASE="rowstore-webapp-$VERSION" && echo $FILE_BASE
          - ( cd webapp/target/ && sha256sum ${FILE_BASE}.war > ${FILE_BASE}.war.sha256 && gpg --clearsign --default-key 4C12C06EE69EBA383C1A47C61010232068FF1D01 ${FILE_BASE}.war.sha256 )
          - scp -v webapp/target/{*.war,*.sha256.asc} standalone/target/dist/{*.tar.gz,*.sha256.asc} deploy@meta1.metasolutions.se:/var/www/entrystore.org/download/rowstore/
          - if [ $BITBUCKET_BRANCH == "develop" ]; then ssh deploy@meta1.metasolutions.se "echo $VERSION > /var/www/entrystore.org/download/rowstore/develop.version" ; elif [ $BITBUCKET_BRANCH == "master" ]; then ssh deploy@meta1.metasolutions.se "echo $VERSION > /var/www/entrystore.org/download/rowstore/latest.version" ; fi
          - rm -rf ~/.m2/repository/org/entrystore/
