image: metasolutions/jdk-node

options:
  max-time: 10

stepdefinitions:
  - build: &build
      name: Build
      caches:
        - maven
      script:
        - java -version
        - mvn --version
        - mvn clean install
        - rm -rf ~/.m2/repository/org/entrystore/
      artifacts:
        - standalone/jetty/target/**
  - testpg: &testpg
      name: Integration Test PostgreSQL
      script:
        - chmod +x standalone/jetty/target/dist/bin/rowstore
        - standalone/jetty/target/dist/bin/rowstore --config file://$PWD/tests/rowstore_tests_postgres.json --port 8282 &
        - sleep 5
        - cd tests
        - npm install -g jasmine-node
        - npm install frisby@0.8.5
        - jasmine-node .
      services:
        - postgres
  - testcr: &testcr
      name: Integration Test CockroachDB
      script:
        - chmod +x standalone/jetty/target/dist/bin/rowstore
        - standalone/jetty/target/dist/bin/rowstore --config tests/rowstore_tests_cockroach.json --port 8282 &
        - sleep 5
        - cd tests
        - npm install -g jasmine-node
        - npm install frisby@0.8.5
        - jasmine-node .
      services:
        - cockroach
  - deploy: &deploy
      name: Deploy
      script:
        - gpg --version
        - echo $GPG_SIGN_KEY | base64 -d | gpg --import
        - gpg --list-secret-keys
        - export VERSION=`cat VERSION.txt` && echo $VERSION
        # We allow semantic versioning plus x.y-z (e.g. 4.10-SNAPSHOT which does not exactly conform to semver)
        - echo $VERSION | grep -P -q '^(0|[1-9]\d*)\.(0|[1-9]\d*)(\.*)(0*|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
        - export FILE_BASE="rowstore-jetty-$VERSION" && echo $FILE_BASE
        - ( cd standalone/jetty/target/dist/ && tar czf ${FILE_BASE}.tar.gz * && sha256sum ${FILE_BASE}.tar.gz > ${FILE_BASE}.tar.gz.sha256 && gpg --clearsign --default-key 4C12C06EE69EBA383C1A47C61010232068FF1D01 ${FILE_BASE}.tar.gz.sha256 )
        - scp -v standalone/jetty/target/dist/{*.tar.gz,*.sha256.asc} deploy@meta1.metasolutions.se:/var/www/entrystore.org/download/rowstore/
        - if [ $BITBUCKET_BRANCH == "develop" ]; then ssh deploy@meta1.metasolutions.se "echo $VERSION > /var/www/entrystore.org/download/rowstore/develop.version" ; elif [ $BITBUCKET_BRANCH == "master" ]; then ssh deploy@meta1.metasolutions.se "echo $VERSION > /var/www/entrystore.org/download/rowstore/latest.version" ; fi
  - dockerhub: &dockerhub
      name: Docker Hub
      script:
        - docker version
        - export VERSION=`cat VERSION.txt` && echo $VERSION
        - export VERSION_MAJOR_MINOR=${VERSION%.*} && echo $VERSION_MAJOR_MINOR
        - git clone -b master git@bitbucket.org:metasolutions/docker.git
        - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
        - cd docker/rowstore
        - ls -l
        - docker build --build-arg ROWSTORE_VERSION=$VERSION --pull --no-cache --tag metasolutions/rowstore:$VERSION .
        - docker push metasolutions/rowstore:$VERSION
        - if [ $BITBUCKET_BRANCH == "develop" ]; then docker tag metasolutions/rowstore:$VERSION metasolutions/rowstore:develop ; docker push metasolutions/rowstore:develop ; fi
        - if [ $BITBUCKET_BRANCH == "master" ]; then docker tag metasolutions/rowstore:$VERSION metasolutions/rowstore:$VERSION_MAJOR_MINOR ; docker push metasolutions/rowstore:$VERSION_MAJOR_MINOR ; fi
      services:
        - docker
      caches:
        - docker

pipelines:
  default:
    - step: *build
    - parallel:
      - step: *testpg
      #- step: *testcr
  branches:
    master:
      - step: *build
      - parallel:
        - step: *testpg
        #- step: *testcr
      - step: *deploy
      - step: *dockerhub
    develop:
      - step: *build
      - parallel:
        - step: *testpg
        #- step: *testcr
      - step: *deploy
      - step: *dockerhub

definitions:
  services:
    postgres:
      image: postgres:12
      variables:
        POSTGRES_DB: 'rowstoretest'
        POSTGRES_USER: 'rowstoretest'
        POSTGRES_PASSWORD: 'rowstoretestpw'
    cockroach:
      image: metasolutions/crdb-single-insecure
