# This is a sample build configuration for Maven.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
image: jimador/docker-jdk-8-maven-node

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - mvn --version
          - mvn clean install
          - cd tests
          - npm install -g jasmine-node
          - npm install --save-dev frisby
          - jasmine-node .