server.port=8282
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
management.endpoints.web.exposure.include=health,info,metrics
server.server-header=RowStore
spring.threads.virtual.enabled=true
spring.main.banner-mode=off
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
